### ISSUE TITLE
UIMenuController - When adding custom action Crashes when cell deallocates 

### ISSUE THREAD

**Issue by testestatic** [QuickBlox/QMChatViewController-ios#66] opened 2016-06-10 11:56 UTC
//iOS version- 9.3, Quickblox iOS SDK version- 2.0, QMChatViewController version- Latest

// Problem :- When I use UIMenuController to navigate to any view controller and when I navigate back to ChatView and pop to dialogue view It crashes because of ChatCell is been Deallocated .

Example : - create a forward menuController Item and just navigate to any view controller and just click on back to chat view controller and then back to recent chat view controller 

// in QMChatViewController.m
`- (void)viewDidLoad {

```
[super viewDidLoad];

[[[self class] nib] instantiateWithOwner:self options:nil];

[self configureMessagesViewController];
[self registerForNotifications:YES];

//Customize your toolbar buttons
self.inputToolbar.contentView.leftBarButtonItem = [self accessoryButtonItem];
self.inputToolbar.contentView.rightBarButtonItem = [self sendButtonItem];
[QMChatCell registerMenuAction:@selector(forward:)];
self.collectionView.transform = CGAffineTransformMake(1, 0, 0, -1, 0, 0);
```

}`

`- (void)didReceiveMenuWillShowNotification:(NSNotification *)notification {

```
if (!self.selectedIndexPathForMenu) {
    return;
}

[[NSNotificationCenter defaultCenter] removeObserver:self
                                                name:UIMenuControllerWillShowMenuNotification
                                              object:nil];

UIMenuController *menu = [notification object];
[menu setMenuVisible:NO animated:NO];

selectedCell = (QMChatCell *)[self.collectionView cellForItemAtIndexPath:self.selectedIndexPathForMenu] ;
CGRect selectedCellMessageBubbleFrame = [selectedCell convertRect:selectedCell.containerView.frame toView:self.view];

UIMenuItem *forward = [[UIMenuItem alloc] initWithTitle:@"forward" action:@selector(forward:)];


[menu setMenuItems:[NSArray arrayWithObjects:forward,nil]];
[menu setTargetRect:selectedCellMessageBubbleFrame inView:self.view];
[menu setMenuVisible:YES animated:YES];

[[NSNotificationCenter defaultCenter] addObserver:self
                                         selector:@selector(didReceiveMenuWillShowNotification:)
                                             name:UIMenuControllerWillShowMenuNotification
                                           object:nil];
```

}`

// In chatViewController.m

`- (BOOL)collectionView:(UICollectionView *)collectionView canPerformAction:(SEL)action forItemAtIndexPath:(NSIndexPath *)indexPath withSender:(id)sender {

```
return action == @selector(copy:) || action == @selector(forward:) ;
```

}`

`- (void)chatCell:(QMChatCell *)cell didPerformAction:(SEL)action withSender:(id)sender {

```
NSIndexPath *indexPath = [self.collectionView indexPathForCell:cell];

QBChatMessage *message = [self.chatSectionManager messageForIndexPath:indexPath];

if ([NSStringFromSelector(action) isEqualToString:@"forward:"]) {
    //NSLog(@"hhhhhh");
    [self performSegueWithIdentifier:@"forwardMessage"  sender:nil];
}
```

}
`

**It works perfectly I can get the action and can able to perform segue(Push segue) , but when I pop to chat view and when pop back to list of dialogues it crashes**

**Did this work before? -- NO**

Logs :--- 

**\* -[QMChatIncomingCell release]: message sent to deallocated instance 0x7fc8cc4f6b60
![screen shot 2016-06-10 at 5 25 22 pm](https://cloud.githubusercontent.com/assets/19856018/15963531/5dcb59fe-2f30-11e6-8acb-4ab58b53545f.png)

**Comment by testestatic** [comment] 2016-06-14 05:18
Hello @VitaliyGuru  , 

Did you get what exactly the problem We are facing ? If you have any confusion please ask me

**Comment by testestatic** [comment] 2016-07-04 08:07
Still No Answer ??? @VitaliyGuru @Raikerian

**Comment by Raikerian** [comment] 2016-11-14 12:09
@testestatic do you still have this issue? It's working fine for us.

**Comment by Raikerian** [comment] 2016-11-30 10:36
@testestatic any updates?

**Comment by Raikerian** [comment] 2016-12-14 15:59
Closing due to lack of user response. If you are still having this issue, create a new thread and attach some kind of sample project with this issue being reproducible. Cause we do not have such problems in our sample.

**Closed as completed by Raikerian** 2016-12-14 15:59 UTC
Labels: help wanted
